### ISSUE TITLE
fatalError()

### ISSUE THREAD

**Issue by TrondKjeldas** [naoty/SwiftCSV#37] opened 2016-05-14 15:41 UTC
If I'm feeding in a corrupt file it ends up calling fatalError() instead of throwing, hence my app can't gracefully deal with the failure.

Is this intentional?

**Comment by gavanchan** [comment] 2016-07-06 12:13
Would you be able to provide the corrupt file?

If the file is big and/or there are multiple corruptions, would you also be able to point out the lines?

**Comment by grantkemp** [comment] 2017-01-18 22:59
@TrondKjeldas  can you give an example so we can replicate it? If not- lets close this till its reproduceable.

**Comment by grantkemp** [comment] 2017-01-29 17:12
Closed due to no response

**Closed** 2017-01-29 17:12 UTC

**Comment by tkrajacic** [comment] 2017-02-10 14:08
Well, I can contribute to this.

The library can't handle providing a wrong delimiter and instead of throwing it crashes.

For example
`let csv = CSV(string: "\"Email Address\",\"First Name\",\"Last Name\",Strasse", delimiter: ";", loadColumns: false)` 
crashes inside
`change(_ char: Character)`
instead of somehow realizing that the line cannot be parsed, as there is not a single delimiter character before encountering a newline.

I guess this is what the original reporter could have meant.

Please reopen this issue.

**Comment by TrondKjeldas** [comment] 2017-02-16 18:44
Sorry for the late reply.

The problem is in Parser.swift, these calls:  fatalError("Can't have non-quote here: \(char)")

This call causes the application to terminate!

In my opinion a library should throw an exception when encountering an error in the input, thus allowing the application using the library to gracefully handle the error ( i.e. by informing the user that the file is corrupt.)

**Comment by ThoseGuysInTown** [comment] 2019-08-15 10:10
I definitely agree with @TrondKjeldas, I now have to build out my own way to validate the data based on how SwiftCSV is parsing the data. :( 
Great library otherwise! 
@TrondKjeldas and @tkrajacic how have you all dealt with this issue?
